version: '3.2'
services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
    - 9093:9093
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    depends_on:
    - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./alert.rules:/etc/prometheus/alert.rules:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6739:6739